version: '3.3'

services:
   db:
     image: sergeyivanov/mysql-server-practicalmicroservice:5.7
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root@localhost
       MYSQL_DATABASE: practicalmicroservice
       MYSQL_USER: mysql
       MYSQL_PASSWORD: root@localhost
       MYSQL_ROOT_HOST: 127.0.0.1
     ports:
       - "3307:3306"

